project_id = "wehareeowwpsoztkrvle"

[functions.google-directions]
verify_jwt = false

[functions.fetch-weather]
verify_jwt = false

[functions.parse-flight-booking]
verify_jwt = false

[functions.auto-generate-transport]
verify_jwt = false
